# nothing here
# Enable Hardware Floating Point Unit
CONFIG_FPU=y

# Enable Float formatting for print statements (useful for debugging)
CONFIG_CBPRINTF_FP_SUPPORT=y

# Turn on the serial port and console switches
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
