"""
Export test data from pkl to C arrays

Produces: test_data.h

Run:
    python export_test_data.py

Then copy test_data.h into your Zephyr project src/ folder.
"""

import os
import numpy as np
import pandas as pd

BASE_PATH      = r"C:\Users\Fathi\pw"
FILE_NAME      = "09_filtered_all_data.pkl"
FULL_PATH      = os.path.join(BASE_PATH, FILE_NAME)
OUTPUT_PATH    = os.path.join(BASE_PATH, "test_data.h")

WINDOW_SIZE    = 410
STEP_SIZE      = 102
TRAIN_RATIO    = 0.8
N_TEST_WINDOWS = 10

IMU_SUFFIXES   = ["-f", "-c", "-q", "-h"]
GONIO_TARGETS  = ['G_DA_X', 'G_DA_Y', 'G_DK_X', 'G_DK_Y', 'G_NDA_X', 'G_NDA_Y']

print(f"Loading {FULL_PATH} ...")
df = pd.read_pickle(FULL_PATH)
df[df.select_dtypes('float64').columns] = df.select_dtypes('float64').astype('float32')
df['Activity'] = df['Activity'].str.rstrip('_')
print(f"  Shape: {df.shape[0]:,} rows x {df.shape[1]} cols")

imu_cols   = [c for c in df.columns if any(s in c for s in IMU_SUFFIXES)]
ta_cols    = [c for c in df.columns if 'EMG_TA' in c]
gm_cols    = [c for c in df.columns if 'EMG_GM' in c]
gonio_cols = [c for c in GONIO_TARGETS if c in df.columns]

N_IMU_CH  = len(imu_cols)
N_OUTPUTS = len(gonio_cols)
has_emg   = len(ta_cols) > 0 and len(gm_cols) > 0

print(f"  IMU channels : {N_IMU_CH}")
print(f"  Gonio cols   : {gonio_cols}")
print(f"  EMG available: {has_emg}")

imu_data   = df[imu_cols].to_numpy(dtype=np.float32)
gonio_data = df[gonio_cols].to_numpy(dtype=np.float32)
if has_emg:
    ta_data = df[ta_cols].to_numpy(dtype=np.float32)
    gm_data = df[gm_cols].to_numpy(dtype=np.float32)


def extract_rf_features(start):
    end       = start + WINDOW_SIZE
    w_imu     = imu_data[start:end]
    imu_means = np.mean(w_imu, axis=0)
    if has_emg:
        ta_mav = float(np.mean(np.abs(ta_data[start:end])))
        gm_mav = float(np.mean(np.abs(gm_data[start:end])))
    else:
        ta_mav = 0.0
        gm_mav = 0.0
    return np.array([ta_mav, gm_mav] + imu_means.tolist(), dtype=np.float32)


split_idx        = int(len(df) * TRAIN_RATIO)
rf_features_list = []
raw_imu_list     = []
true_list        = []

collected = 0
for start in range(split_idx, len(df) - WINDOW_SIZE, STEP_SIZE):
    if collected >= N_TEST_WINDOWS:
        break
    rf_features_list.append(extract_rf_features(start))
    raw_imu_list.append(imu_data[start:start+WINDOW_SIZE].copy())
    true_list.append(np.mean(gonio_data[start:start+WINDOW_SIZE], axis=0))
    collected += 1

print(f"\nCollected {collected} test windows")


def row_to_c(arr):
    return ", ".join(f"{float(v):.8f}f" for v in arr.flatten())


with open(OUTPUT_PATH, 'w') as f:
    f.write("/* AUTO-GENERATED by export_test_data.py */\n\n")
    f.write("#ifndef TEST_DATA_H\n#define TEST_DATA_H\n\n")
    f.write(f"#define TEST_N_WINDOWS    {collected}\n")
    f.write(f"#define TEST_N_FEATURES   {len(rf_features_list[0])}\n")
    f.write(f"#define TEST_N_OUTPUTS    {N_OUTPUTS}\n")
    f.write(f"#define TEST_WINDOW_SIZE  {WINDOW_SIZE}\n")
    f.write(f"#define TEST_N_IMU_CH     {N_IMU_CH}\n\n")

    # RF features
    n_feat = len(rf_features_list[0])
    f.write(f"/* RF pre-computed features [{collected}][{n_feat}] */\n")
    f.write(f"static const float test_features[{collected}][{n_feat}] = {{\n")
    for i, feats in enumerate(rf_features_list):
        f.write(f"    /* w{i} */ {{{row_to_c(feats)}}},\n")
    f.write("};\n\n")

    # Raw IMU windows (flat)
    flat_size = WINDOW_SIZE * N_IMU_CH
    f.write(f"/* Raw IMU windows [{collected}][{flat_size}] for ANN */\n")
    f.write(f"static const float test_imu_windows[{collected}][{flat_size}] = {{\n")
    for i, win in enumerate(raw_imu_list):
        f.write(f"    /* w{i} */ {{{row_to_c(win)}}},\n")
    f.write("};\n\n")

    # Ground truth
    f.write(f"/* Ground truth [{collected}][{N_OUTPUTS}] */\n")
    f.write(f"/* Order: {', '.join(gonio_cols)} */\n")
    f.write(f"static const float test_true_outputs[{collected}][{N_OUTPUTS}] = {{\n")
    for i, true in enumerate(true_list):
        f.write(f"    /* w{i} */ {{{row_to_c(true)}}},\n")
    f.write("};\n\n#endif\n")

kb = os.path.getsize(OUTPUT_PATH) / 1024
print(f"Written: {OUTPUT_PATH}  ({kb:.1f} KB)")
print("Copy test_data.h into your Zephyr src/ folder")
